# Installation outside of nix home-manager
# docker
# nerd font
# google chrome
# home-manager
# brew 
# warp
# no action when press fn
# only switch keyboard mode with globe sign
# homerow

# Optional
# davinci-resolve-studio
# capcut
