# Installation outside of nix home-manager
# docker 
# wezterm
# nerd font
# google chrome
# home-manager
# brew 
# warp
# no special char when press option key
# no action when press fn
# only switch keyboard mode with ctrol+option+space