# Brewfile for installing applications

# CLI tools
cask "docker"
cask "tailscale"

# Fonts
cask "font-jetbrains-mono-nerd-font"

# Browsers
cask "brave-browser"
cask "google-chrome"

# Video editing and production
cask "capcut"
# cask "davinci-resolve" # davinci-resolve is not available on brew

# Productivity tools
cask "raycast"
cask "homerow"
cask "rectangle"

# Creative tools
cask "blender"
cask "obs"
cask "obsidian"
