
.PHONY: all
all: setup-vscode


.PHONY: install
install:
	@echo "Installing..."
	@dnf install -y jq yq ffmpeg fzf direnv bat tmux tmate yt-dlp exa ripgrep thefuck tldr diff-so-fancy z xclip copyq parallel starship
	

.PHONY: setup-vscode
setup-vscode:
	@echo "Setting up VSCode..."

.PHONY: clean
clean:
	@echo "Cleaning up..."
